name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.24.5
  NODE_VERSION: 22

jobs:
  # Build Job
  build:
    strategy:
      matrix:
        feature: [
          "browsers",
          "build-essential",
          "cypress-deps",
          "docker-out",
          "dotnet",
          "eclipse-deps",
          "git-lfs",
          "gitlab-cli",
          "go",
          "gonovate",
          "goreleaser",
          "instant-client",
          "jfrog-cli",
          "kubectl",
          "locale",
          "make",
          "mingw",
          "nginx",
          "node",
          "nvidia-cuda",
          "playwright-deps",
          "python",
          "rust",
          "sonar-scanner-cli",
          "system-packages",
          "timezone",
          "vault-cli",
          "zig"
        ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          go-version: ${{ env.GO_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: go run ./build --target "Feature:${{ matrix.feature }}:Package"

      - name: Test
        run: go run ./build --target "Feature:${{ matrix.feature }}:Test"

  # Publish Job
  publish:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-env
        with:
          go-version: ${{ env.GO_VERSION }}
          node-version: ${{ env.NODE_VERSION }}

      - name: Publish
        run: go run ./build --target "Features:Publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
