name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.24.5

jobs:
  # Build Job
  build:
    strategy:
      matrix:
        feature: [
          "browsers",
          "build-essential",
          "cypress-deps",
          "docker-out",
          "eclipse-deps",
          "git-lfs",
          "gitlab-cli",
          "go",
          "goreleaser",
          "instant-client",
          "jfrog-cli",
          "locale",
          "make",
          "mingw",
          "nginx",
          "node",
          "playwright-deps",
          "timezone",
          "vault-cli",
          "zig"
        ]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.GO_VERSION }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup DevContainer-CLI
        run: npm install -g @devcontainers/cli

      - name: Build
        run: go run ./build --target "Feature:${{ matrix.feature }}:Package"

      - name: Test
        run: go run ./build --target "Feature:${{ matrix.feature }}:Test"
      
      - name: Publish
        if: github.ref == 'refs/heads/main'
        run: go run ./build --target "Feature:${{ matrix.feature }}:Publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
