name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: 1.24.5

jobs:
  # Build Job
  build:
    strategy:
      matrix:
        feature: ["go"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ vars.GO_VERSION }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup DevContainer-CLI
        run: npm install -g @devcontainers/cli

      - name: Build
        run: go run ./build --target "Feature:${{ matrix.feature }}:Package"
